# Generated by Django 5.0.2 on 2025-02-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
